//import randomAppointments from "./randomAppointments";

export const dentists = [
  {
    firstName: "Keven",
    lastName: "Rawlence",
    phone: "9366029657",
    email: "keven.rawlence@dentistcompanybvt.com",
    sick: false,
  },
  {
    firstName: "Sherline",
    lastName: "Pascoe",
    phone: "2366192618",
    email: "sherline.pascoe@dentistcompanybvt.com",
    sick: false,
  },
  {
    firstName: "Karia",
    lastName: "Fountaine",
    phone: "2939205258",
    email: "karia.fountaine@dentistcompanybvt.com",
    sick: true,
  },
  {
    firstName: "Shirlee",
    lastName: "Varren",
    phone: "9064543760",
    email: "shirly.varren@dentistcompanybvt.com",
    sick: true,
  },
];
export const assistants = [
  {
    firstName: "Oberon",
    lastName: "Babber",
    phone: "9752269673",
    email: "oberon.babber@dentistcompanybvt.com",
    sick: false,
  },
  {
    firstName: "Gavra",
    lastName: "Seacroft",
    phone: "7814487556",
    email: "gavra.seacroft@dentistcompanybvt.com",
    sick: true,
  },
];
export const clients = [
  {
    firstName: "Eleen",
    lastName: "Chitson",
    phone: "4104717536",
    email: "echitson6@answers.com",
    birthYear: 1967,
    sick: false,
  },
  {
    firstName: "Madelle",
    lastName: "Brazer",
    phone: "2751153346",
    email: "mbrazer7@themeforest.net",
    birthYear: 1992,
    sick: false,
  },
  {
    firstName: "Yalonda",
    lastName: "Gon",
    phone: "3054827838",
    email: "ygon8@epa.gov",
    birthYear: 1982,
    sick: true,
  },
  {
    firstName: "Hephzibah",
    lastName: "Aish",
    phone: "4064234353",
    email: "haish9@cisco.com",
    birthYear: 1998,
    sick: false,
  },
  {
    firstName: "Jeromy",
    lastName: "Reuven",
    phone: "6645511714",
    email: "jreuvena@examiner.com",
    birthYear: 2010,
    sick: false,
  },
  {
    firstName: "Bernarr",
    lastName: "Simpole",
    phone: "7873612300",
    email: "bsimpoleb@barnesandnoble.com",
    birthYear: 1989,
    sick: false,
  },
  {
    firstName: "Coral",
    lastName: "Stelfox",
    phone: "2938982275",
    email: "cstelfoxc@pinterest.com",
    birthYear: 1958,
    sick: false,
  },
  {
    firstName: "Lukas",
    lastName: "Screwton",
    phone: "7574343779",
    email: "lscrewtond@slideshare.net",
    birthYear: 2004,
    sick: false,
  },
  {
    firstName: "See",
    lastName: "Callam",
    phone: "6466700834",
    email: "scallame@redcross.org",
    birthYear: 1981,
    sick: false,
  },
  {
    firstName: "Niven",
    lastName: "Lumpkin",
    phone: "4685147985",
    email: "nlumpkinf@ftc.gov",
    birthYear: 1971,
    sick: true,
  },
  {
    firstName: "Vita",
    lastName: "Hablot",
    phone: "4495119215",
    email: "vhablotg@imdb.com",
    birthYear: 2004,
    sick: false,
  },
  {
    firstName: "Cindelyn",
    lastName: "Varty",
    phone: "2509180497",
    email: "cvartyh@princeton.edu",
    birthYear: 1981,
    sick: false,
  },
  {
    firstName: "Binny",
    lastName: "Lineker",
    phone: "3918512622",
    email: "blinekeri@biblegateway.com",
    birthYear: 1980,
    sick: false,
  },
  {
    firstName: "Donielle",
    lastName: "Bilton",
    phone: "8094218760",
    email: "dbiltonj@domainmarket.com",
    birthYear: 1989,
    sick: true,
  },
  {
    firstName: "Riva",
    lastName: "Pawelke",
    phone: "2229455354",
    email: "rpawelkek@imgur.com",
    birthYear: 2013,
    sick: false,
  },
  {
    firstName: "Nyssa",
    lastName: "Bradane",
    phone: "2864766706",
    email: "nbradanel@about.me",
    birthYear: 2001,
    sick: false,
  },
  {
    firstName: "Cordelia",
    lastName: "Merriday",
    phone: "1993169232",
    email: "cmerridaym@infoseek.co.jp",
    birthYear: 1982,
    sick: false,
  },
  {
    firstName: "Karly",
    lastName: "MacPeice",
    phone: "8944101351",
    email: "kmacpeicen@tinypic.com",
    birthYear: 2001,
    sick: true,
  },
  {
    firstName: "Meriel",
    lastName: "Guiton",
    phone: "6186860858",
    email: "mguitono@unesco.org",
    birthYear: 1968,
    sick: true,
  },
  {
    firstName: "George",
    lastName: "Dudleston",
    phone: "1088784701",
    email: "gdudlestonp@icio.us",
    birthYear: 1998,
    sick: false,
  },
  {
    firstName: "Gerrie",
    lastName: "Scryne",
    phone: "5453563711",
    email: "gscryneq@yolasite.com",
    birthYear: 1957,
    sick: true,
  },
  {
    firstName: "Cinnamon",
    lastName: "Flasby",
    phone: "1222165905",
    email: "cflasbyr@washington.edu",
    birthYear: 2012,
    sick: true,
  },
  {
    firstName: "Vitoria",
    lastName: "McKernan",
    phone: "1425734815",
    email: "vmckernans@facebook.com",
    birthYear: 1992,
    sick: true,
  },
  {
    firstName: "Datha",
    lastName: "Sabben",
    phone: "4759241287",
    email: "dsabbent@google.com.au",
    birthYear: 1977,
    sick: true,
  },
  {
    firstName: "Amanda",
    lastName: "Korf",
    phone: "8893521174",
    email: "akorfu@patch.com",
    birthYear: 1970,
    sick: false,
  },
  {
    firstName: "Humphrey",
    lastName: "Dorgan",
    phone: "8283689603",
    email: "hdorganv@economist.com",
    birthYear: 1999,
    sick: true,
  },
  {
    firstName: "Pierce",
    lastName: "Bagster",
    phone: "7784414222",
    email: "pbagsterw@surveymonkey.com",
    birthYear: 1998,
    sick: false,
  },
  {
    firstName: "Lucita",
    lastName: "Ralston",
    phone: "1308245718",
    email: "lralstonx@apache.org",
    birthYear: 1993,
    sick: true,
  },
  {
    firstName: "Manya",
    lastName: "Micallef",
    phone: "7852116158",
    email: "mmicallefy@umn.edu",
    birthYear: 1983,
    sick: false,
  },
  {
    firstName: "Artur",
    lastName: "Benitez",
    phone: "1398176890",
    email: "abenitezz@about.com",
    birthYear: 2001,
    sick: false,
  },
  {
    firstName: "Mandy",
    lastName: "Amyes",
    phone: "3469919073",
    email: "mamyes10@rakuten.co.jp",
    birthYear: 2000,
    sick: false,
  },
  {
    firstName: "Angele",
    lastName: "Cuncarr",
    phone: "9512741834",
    email: "acuncarr11@illinois.edu",
    birthYear: 1998,
    sick: false,
  },
  {
    firstName: "Evaleen",
    lastName: "Schimank",
    phone: "1326118650",
    email: "eschimank12@creativecommons.org",
    birthYear: 1960,
    sick: false,
  },
  {
    firstName: "Binky",
    lastName: "Lipmann",
    phone: "3802809675",
    email: "blipmann13@wordpress.org",
    birthYear: 2009,
    sick: false,
  },
  {
    firstName: "Jake",
    lastName: "Ilsley",
    phone: "5524920326",
    email: "jilsley14@printfriendly.com",
    birthYear: 1961,
    sick: true,
  },
  {
    firstName: "Eberhard",
    lastName: "Iddenden",
    phone: "4063536226",
    email: "eiddenden15@constantcontact.com",
    birthYear: 2005,
    sick: true,
  },
  {
    firstName: "Gaile",
    lastName: "Seeger",
    phone: "9647620521",
    email: "gseeger16@histats.com",
    birthYear: 1967,
    sick: true,
  },
  {
    firstName: "Adela",
    lastName: "Bakhrushin",
    phone: "8944619543",
    email: "abakhrushin17@scientificamerican.com",
    birthYear: 1971,
    sick: false,
  },
  {
    firstName: "Prudi",
    lastName: "Golson",
    phone: "9039101184",
    email: "pgolson18@xrea.com",
    birthYear: 1988,
    sick: false,
  },
  {
    firstName: "Jessamine",
    lastName: "Checo",
    phone: "3086787958",
    email: "jcheco19@bluehost.com",
    birthYear: 1981,
    sick: false,
  },
  {
    firstName: "Odie",
    lastName: "Kolodziejski",
    phone: "2983716230",
    email: "okolodziejski1a@bizjournals.com",
    birthYear: 1968,
    sick: true,
  },
  {
    firstName: "Joachim",
    lastName: "Bampton",
    phone: "8858412452",
    email: "jbampton1b@usda.gov",
    birthYear: 1976,
    sick: false,
  },
  {
    firstName: "Cathleen",
    lastName: "Plowright",
    phone: "7834467305",
    email: "cplowright1c@hc360.com",
    birthYear: 1985,
    sick: false,
  },
  {
    firstName: "Kincaid",
    lastName: "Pigot",
    phone: "8269031365",
    email: "kpigot1d@usda.gov",
    birthYear: 1992,
    sick: false,
  },
  {
    firstName: "Rickey",
    lastName: "Gabe",
    phone: "9424185099",
    email: "rgabe1e@loc.gov",
    birthYear: 2008,
    sick: false,
  },
  {
    firstName: "Francklin",
    lastName: "Ravel",
    phone: "3627435778",
    email: "fravel1f@google.pl",
    birthYear: 2014,
    sick: true,
  },
  {
    firstName: "Abby",
    lastName: "Chang",
    phone: "3694696248",
    email: "achang1g@constantcontact.com",
    birthYear: 2008,
    sick: true,
  },
  {
    firstName: "Tirrell",
    lastName: "Headingham",
    phone: "9487352042",
    email: "theadingham1h@oakley.com",
    birthYear: 1997,
    sick: false,
  },
  {
    firstName: "Vivianne",
    lastName: "Tattam",
    phone: "1689626464",
    email: "vtattam1i@google.cn",
    birthYear: 2006,
    sick: false,
  },
  {
    firstName: "Cristen",
    lastName: "Durbann",
    phone: "1879500832",
    email: "cdurbann1j@independent.co.uk",
    birthYear: 1993,
    sick: true,
  },
];
export const appointments = []; //randomAppointments;
